#!/bin/bash

echo "Unmounting /mnt and all children"
umount -R /mnt 2&> /dev/null

echo "Mouting EPS to /mnt"
mount /dev/sda1 /mnt

echo "Copying files to /boot/EFI/kali"
cp -v /vmlinuz /initrd.img /mnt/EFI/kali/.

echo "Cleaning up"
umount -R /mnt
